var route = {
  "/doc" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/index.html",
  "/doc/#file-md" : "https://api.github.com/repos/sciola-framework/documentation/contents/framework/file.md",
  "/doc/#requirements" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/requirements.html",
  "/doc/#installation" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/installation.html",
  "/doc/#config" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/config.html",
  "/doc/#database" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/database.html",
  "/doc/#languages" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/languages.html",
  "/doc/#layers" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/layers.html",
  "/doc/#libraries" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/libraries.html",
  "/doc/#packages" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/packages.html",
  "/doc/#public" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/public.html",
  "/doc/#routes" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/routes.html",
  "/doc/#tests" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/tests.html",
  "/doc/#writable" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/directory_structure/writable.html",
  "/doc/#ajax" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/front_end/ajax.html",
  "/doc/#css" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/front_end/css.html",
  "/doc/#js" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/front_end/js.html",
  "/doc/#filters" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/twig/filters.html",
  "/doc/#functions" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/twig/functions.html",
  "/doc/#layout" : "https://raw.githubusercontent.com/sciola-framework/documentation/main/framework/twig/layout.html"
}
